Repository nextcloud/vm, pull requests merged in 2020-10, with the labels that each got.

#1551 create geoblock.sh
  menu/server_configuration.sh
  network/geoblock.sh
Labels: 3. to review

#1550 notify users about started Nextcloud update
  lib.sh
  nextcloud_update.sh
Labels: 3. to review

#1493 make all scripts much more readable
  addons/automatic_updates.sh
  addons/locate_mirror.sh
  addons/redis-server-ubuntu.sh
  apps/adminer.sh
  apps/bitwarden-rs.sh
  apps/bitwarden-rs_admin-panel.sh
  apps/bitwarden_mailconfig.sh
  apps/collabora_docker.sh
  apps/collabora_integrated.sh
  apps/fail2ban.sh
  apps/fulltextsearch.sh
  apps/netdata.sh
  apps/onlyoffice_docker.sh
  apps/onlyoffice_integrated.sh
  apps/previewgenerator.sh
  apps/smbmount.sh
  apps/talk.sh
  apps/talk_signaling.sh
  apps/tmbitwarden.sh
  apps/webmin.sh
  disk/format-chosen.sh
  disk/format-sdb.sh
  disk/prune_zfs_snaphots.sh
  disk/smartctl.sh
  lets-encrypt/activate-tls.sh
  lets-encrypt/test-new-config.sh
  lib.sh
  menu/additional_apps.sh
  menu/nextcloud_configuration.sh
  menu/server_configuration.sh
  menu/startup_configuration.sh
  network/ddclient-configuration.sh
  network/static_ip.sh
  nextcloud-startup-script.sh
  nextcloud_install_production.sh
  nextcloud_update.sh
  not-supported/smbserver.sh
  old/format-sda-nuc-server.sh
  old/spreedme.sh
  static/adduser.sh
  static/cookielifetime.sh
  static/docker_overlay2.sh
  static/fetch_lib.sh
  static/test_connection.sh
  static/updatenotification.sh
Labels: 4. to release

#1554 rework some popups
  addons/smtp-mail.sh
  apps/adminer.sh
  apps/bitwarden_mailconfig.sh
  apps/clamav.sh
  apps/smbmount.sh
  apps/webmin.sh
  lib.sh
  network/geoblock.sh
  not-supported/pi-hole.sh
  not-supported/pivpn.sh
  not-supported/plexmediaserver.sh
  not-supported/remotedesktop.sh
  not-supported/smbserver.sh
Labels: 3. to review

#1558 Update the lib once during the startup script
  menu/startup_configuration.sh
Labels: 3. to review

#1559 fix two small issues
  lib.sh
  menu/server_configuration.sh
Labels: 3. to review

#1549 lvm snapshots - make snapshot failures a bit more informative
  nextcloud_update.sh
Labels: 3. to review

#1571 add duckdns to ddclient and some small enhancements
  network/ddclient-configuration.sh
Labels: 3. to review

#1570 add a msg_box during the startup script to additional_apps
  menu/additional_apps.sh
  menu/server_configuration.sh
Labels: 3. to review

#1569 Add a hint how to cancel whiptail --menu's and --checklist's
  lib.sh
Labels: 3. to review

#1566 add a mechanism to update geoblock database files
  geoblockdat/2020-09-Maxmind-Country-IPv4.dat
  geoblockdat/2020-09-Maxmind-Country-IPv6.dat
  geoblockdat/README.md
  lib.sh
  network/geoblock.sh
  nextcloud_update.sh
Labels: 3. to review

#1580 finalize add a mechanism to update the geoblock database files
  lib.sh
  network/geoblock.sh
  nextcloud_update.sh
Labels: 3. to review

#1581 improve remotedesktop
  not-supported/remotedesktop.sh
Labels: 3. to review

#1579 smtpmail: Allow to not reset all configs and packets at the end of the script
  addons/smtp-mail.sh
Labels: 3. to review

#1583 remotedesktop: fix one small detail
  not-supported/remotedesktop.sh
Labels: 3. to review

#1584 smtp-mail: use echo instead of cat for one-liner
  addons/smtp-mail.sh
Labels: 3. to review

#1588 migrate midnight commander to its own script
  apps/midnight-commander.sh
  menu/additional_apps.sh
Labels: 3. to review

#1592 Some enhancements to some scripts
  apps/bitwarden-rs.sh
  apps/bitwarden_mailconfig.sh
  apps/clamav.sh
  apps/tmbitwarden.sh
Labels: 2. developing

#1591 add Nextcloud to description in additional_apps
  apps/midnight-commander.sh
  menu/additional_apps.sh
Labels: 3. to review

#1593 Update previewgenerator with new function for reinstalling
  apps/previewgenerator.sh
Labels: 3. to review

#1594 update netdata with new function for reinstalling
  apps/netdata.sh
Labels: 3. to review

#1595 update fulltextsearch with new function for reinstalling
  apps/fulltextsearch.sh
  lib.sh
Labels: 3. to review

#1604 Remove msg_box "$SCRIPT_EXPLAINER" where install_popup exists
  addons/smtp-mail.sh
  apps/adminer.sh
  apps/bitwarden-rs.sh
  apps/bpytop.sh
  apps/clamav.sh
  apps/midnight-commander.sh
  apps/netdata.sh
  apps/previewgenerator.sh
  apps/smbmount.sh
  apps/webmin.sh
  network/geoblock.sh
  not-supported/pi-hole.sh
  not-supported/pivpn.sh
  not-supported/plexmediaserver.sh
  not-supported/remotedesktop.sh
  not-supported/smbserver.sh
Labels: 3. to review

#1596 update fail2ban with new function for reinstalling
  apps/fail2ban.sh
Labels: 3. to review

#1605 restore msg_box for bitwarden_rs
  apps/bitwarden-rs.sh
Labels: 3. to review

#1590 fix some issues with smtp-mail
  addons/smtp-mail.sh
Labels: 3. to review

#1598 update talk_signaling with new function for reinstalling
  apps/talk_signaling.sh
Labels: 3. to review

#1599 update onlyoffice_integrated with new function for reinstalling
  apps/onlyoffice_integrated.sh
Labels: 3. to review

#1601 update collabora_integrated with new function for reinstalling
  apps/collabora_integrated.sh
Labels: 3. to review

#1602 update collabora_docker with new function for reinstalling
  apps/collabora_docker.sh
Labels: 3. to review

#1600 update onlyoffice_docker with new function for reinstalling
  apps/onlyoffice_docker.sh
Labels: 3. to review

#1603 update ddclient-configuration with new function for reinstalling
  network/ddclient-configuration.sh
Labels: 3. to review

#1609 Remove the Docker variable since not needed when using start_if_stopped
  nextcloud_update.sh
Labels: 3. to review

#1610 fix some small bugs with talk.sh
  apps/talk.sh
Labels: 3. to review

#1613 remove the last msg_box for talk
  apps/talk.sh
Labels: 3. to review

#1619 smbserver - check for correct permissions and other improvements
  not-supported/smbserver.sh
Labels: 3. to review

#1621 Add two options to the not-supported folder
  not-supported/bitlocker-mount.sh
  not-supported/not-supported_menu.sh
  not-supported/ntfs-mount.sh
Labels: 3. to review, Priority-1

#1625 add an advice to updatenotification
  static/updatenotification.sh
Labels: 3. to review, Priority-2

#1623 update send_mail to feature return values
  lib.sh
Labels: 3. to review, Priority-1

#1622 rename the NcVM-snapshot-update name to NcVM-snapshot-pending
  nextcloud_update.sh
Labels: 3. to review, Priority-1

#1631 update previewgenerator
  apps/previewgenerator.sh
Labels: 3. to review

#1630 fix the fail2ban removal for bitwarden_rs
  apps/fail2ban.sh
Labels: 3. to review

#1637 Fix an issue with clamav
  apps/clamav.sh
Labels: 3. to review

#1632 20.0.1
  CHANGELOG.md
Labels: 4. to release
