Repository nextcloud/vm, pull requests merged in 2020-11, with the labels that each got.

#1639 Add provisioning to format-sdb.sh
  disk/format-sdb.sh
  nextcloud_install_production.sh
Labels: 3. to review

#1640 SMB-Server - Encrypt SMB transfer if AES-NI is enabled
  not-supported/smbserver.sh
Labels: 3. to review

#1643 Update geoblock.sh to get rid of jq
  network/geoblock.sh
Labels: 3. to review, Priority-1

#1644 rename the NOT_SUPPORTED variable to NOT_SUPPORTED_FOLDER
  lib.sh
  not-supported/not-supported.sh
  not-supported/not-supported_menu.sh
Labels: 3. to review, Priority-2

#1645 add a script-explainer to nextcloud_install_production
  nextcloud_install_production.sh
Labels: 3. to review, Priority-1

#1642 smbserver - allow to choose nearly any password again
  not-supported/smbserver.sh
Labels: 3. to review, Priority-1

#1652 ClamAV - add a mechanism to inform about found files
  apps/clamav.sh
Labels: 3. to review

#1653 fix a bug in midnight-commander.sh
  apps/midnight-commander.sh
Labels: 3. to review

#1654 Remotedesktop - Add two more options
  apps/midnight-commander.sh
  not-supported/remotedesktop.sh
Labels: 3. to review

#1650 Create smart-monitoring.sh to allow continuosly smart checking
  disk/smart-monitoring.sh
  disk/smartctl.sh
  menu/server_configuration.sh
Labels: 3. to review

#1655 Add a complete Backup solution to the not-suppported-folder
  not-supported/backup-viewer.sh
  not-supported/borgbackup.sh
  not-supported/daily-backup-wizard.sh
  not-supported/not-supported_menu.sh
  not-supported/offshore-backup-wizard.sh
  not-supported/rsyncbackup.sh
Labels: 3. to review

#1657 fix an issue with ntfs-mount
  not-supported/ntfs-mount.sh
Labels: 3. to review

#1658 Some enhancements to the backup scripts
  not-supported/borgbackup.sh
  not-supported/daily-backup-wizard.sh
  not-supported/offshore-backup-wizard.sh
  not-supported/rsyncbackup.sh
Labels: 3. to review

#1659 fix some more issues with the backup scripts
  not-supported/borgbackup.sh
  not-supported/daily-backup-wizard.sh
  not-supported/offshore-backup-wizard.sh
  not-supported/rsyncbackup.sh
Labels: 3. to review

#1663 previewgenerator - make sure that the cronjob gets created
  apps/previewgenerator.sh
Labels: 3. to review

#1661 Add one option to the not-supported folder
  not-supported/tpm2-unlock.sh
Labels: 3. to review

#1666 Fix travis
  not-supported/tpm2-unlock.sh
Labels: 3. to review

#1677 fix clamav full-scan
  apps/clamav.sh
Labels: 3. to review

#1683 Some improvements and some additions to the not-supported folder
  not-supported/borgbackup.sh
  not-supported/daily-backup-wizard.sh
  not-supported/not-supported_menu.sh
  not-supported/ntfs-format.sh
  not-supported/ntfs-mount.sh
  not-supported/smbserver.sh
  not-supported/veracrypt.sh
Labels: 3. to review

#1685 further improve the clamav full-scan
  apps/clamav.sh
Labels: 3. to review

#1686 improve remotedesktop.sh
  not-supported/remotedesktop.sh
Labels: 3. to review

#1681 allow to reinstall automatic updates
  addons/automatic_updates.sh
Labels: 3. to review

#1692 install_production: improve the partition check
  nextcloud_install_production.sh
Labels: 3. to review

#1641 20.0.2
  CHANGELOG.md
Labels: 3. to review, Overview

#1700 Update geoblock database files
  geoblockdat/2020-11-Maxmind-Country-IPv4.dat
  geoblockdat/2020-11-Maxmind-Country-IPv6.dat
Labels: 3. to review

#1702 Fix PHP error mesage
  nextcloud_update.sh
Labels: 3. to review
