Repository nextcloud/vm, pull requests merged in 2021-08, with the labels that each got.

#2075 Small fix to a script in the not-supported folder
  not-supported/tpm2-unlock.sh
Labels: enhancement, 3. to review

#2045 Update and rename bitwarden-rs.sh to vaultwarden.sh
  apps/bitwarden-rs_admin-panel.sh
  apps/fail2ban.sh
  apps/vaultwarden.sh
  apps/vaultwarden_admin-panel.sh
  lib.sh
  menu/bitwarden_menu.sh
  nextcloud_update.sh
  not-supported/restore-backup.sh
Labels: enhancement, 3. to review

#2076 Remove trusted proxy workaround in remotedesktop
  not-supported/remotedesktop.sh
Labels: enhancement, 3. to review

#2083 improve logging of the bitwarden to vaultwarden update
  nextcloud_update.sh
Labels: 3. to review

#2094 Don't execute the update before all cronjobs are finished
  lib.sh
  nextcloud_update.sh
Labels: 3. to review

#2096 improve the notification on running the update script
  nextcloud_update.sh
Labels: 2. developing

#2097 always create a backup before updating
  nextcloud_update.sh
  not-supported/pi-hole.sh
Labels: 3. to review
