Repository nextcloud/vm, pull requests merged in 2021-05, with the labels that each got.

#1938 smbserver - allow access to btrfs snapshots
  not-supported/smbserver.sh
Labels: 3. to review

#1939 smbserver - use user- and group-variables everywhere
  not-supported/smbserver.sh
Labels: 3. to review

#1950 set retention_obligation to default
  nextcloud_install_production.sh
Labels: 3. to review

#1954 set max_chunk_size by default to 100MB
  nextcloud_install_production.sh
Labels: 3. to review

#1955 smbserver - speed up restart of the service
  not-supported/smbserver.sh
Labels: 3. to review

#1956 clamav - increase scansizes to 1000M
  apps/clamav.sh
Labels: 3. to review

#1957 some improvements to scripts in the not-supported folder
  not-supported/backup-viewer.sh
  not-supported/rsyncbackup.sh
  not-supported/veracrypt-btrfs.sh
Labels: 3. to review

#1958 fix an issue with Nextcloud's external storage app
  not-supported/borgbackup.sh
  not-supported/veracrypt-btrfs.sh
  not-supported/veracrypt-ntfs.sh
Labels: 3. to review

#1961 remotedesktop - add grsync
  not-supported/remotedesktop.sh
Labels: 3. to review

#1968 smbmount - make backup option more understandable
  apps/smbmount.sh
Labels: 3. to review

#1979 POC for regular zfs snapshot prune
  disk/create-daily-zfs-prune.sh
  disk/prune_zfs_snaphots.sh
  nextcloud_install_production.sh
Labels: 3. to review

#1984 smbserver - add option to automatically empty recycle bins
  not-supported/smbserver.sh
Labels: 3. to review

#1985 previewgenerator - allow to clear all previews
  apps/previewgenerator.sh
Labels: 3. to review

#1983 smbserver - add option to empty all recycle bins
  not-supported/smbserver.sh
Labels: 3. to review

#1987 update mimetype list
  nextcloud_update.sh
Labels: 3. to review

#1989 reorganize office scripts
  apps/collabora_docker.sh
  apps/collabora_integrated.sh
  apps/onlyoffice_docker.sh
  apps/onlyoffice_integrated.sh
Labels: 3. to review

#1990 make trusted_domain removal and addition its own function
  apps/collabora_docker.sh
  apps/collabora_integrated.sh
  apps/onlyoffice_docker.sh
  apps/onlyoffice_integrated.sh
  apps/pico_cms.sh
  lib.sh
  not-supported/restore-backup.sh
Labels: 3. to review, enhancement

#2003 geoblock - update link to csv file
  network/geoblock.sh
Labels: 3. to review

#1996 add a function to remove all office apps
  apps/collabora_docker.sh
  apps/collabora_integrated.sh
  apps/onlyoffice_docker.sh
  apps/onlyoffice_integrated.sh
  lib.sh
Labels: 3. to review

#2005 refactor the bitwarden_mailconfig script
  apps/bitwarden_mailconfig.sh
Labels: 2. developing, 3. to review

#2006 add more functionality to curl_to_dir
  apps/face-recognition.sh
  apps/webmin.sh
  lib.sh
Labels: 3. to review

#2011 fix curl_to_dir for use in function
  apps/netdata.sh
  lib.sh
Labels: 4. to release

#2007 docker documentserver - don't restart docker
  apps/collabora_docker.sh
  apps/onlyoffice_docker.sh
Labels: 3. to review
