Repository nextcloud/vm, pull requests merged in 2021-07, with the labels that each got.

#2004 bitwarden - add hint that you need to wait
  apps/bitwarden_mailconfig.sh
  apps/bitwarden_registration.sh
Labels: 2. developing

#1997 Preparations for the next NC22.0.0 NcVM release
  CHANGELOG.md
  apps/collabora_docker.sh
  apps/collabora_integrated.sh
  apps/onlyoffice_docker.sh
  apps/onlyoffice_integrated.sh
  apps/pico_cms.sh
  lib.sh
  nextcloud-startup-script.sh
Labels: 2. developing

#2043 Some small enhancements to the backup scripts
  not-supported/borgbackup.sh
  not-supported/rsyncbackup.sh
Labels: 3. to review

#2065 only update the updatenotification script if a new Nextcloud update is available
  nextcloud_update.sh
Labels: 3. to review

#2066 add deSEC menu
  lib.sh
  menu/desec_menu.sh
  menu/server_configuration.sh
  nextcloud_install_production.sh
Labels: enhancement
