Repository nextcloud/vm, pull requests merged in 2021-04, with the labels that each got.

#1913 improve the built-in backup solution to work with normal NcVM configurations
  apps/smbmount.sh
  menu/server_configuration.sh
  nextcloud_install_production.sh
  nextcloud_update.sh
  not-supported/backup-viewer.sh
  not-supported/borgbackup.sh
  not-supported/daily-backup-wizard.sh
  not-supported/offshore-backup-wizard.sh
  not-supported/restore-backup.sh
  not-supported/system-restore.sh
Labels: 3. to review

#1915 smart-monitoring - fix initial disk check
  disk/smart-monitoring.sh
Labels: 3. to review

#1918 update geoblock database - april
  geoblockdat/2021-04-Maxmind-Country-IPv4.dat
  geoblockdat/2021-04-Maxmind-Country-IPv6.dat
Labels: 3. to review

#1912 speed up the network check if the network already works
  lib.sh
Labels: 3. to review

#1920 Add DNS updates with deSEC
  addons/desec.sh
  lets-encrypt/activate-tls.sh
Labels: 2. developing, Priority-1, enhancement

#1919 21.0.1
  CHANGELOG.md
Labels: 3. to review

#1924 Add automatic snapshot unlocking upon reboot
  nextcloud_update.sh
  not-supported/backup-viewer.sh
  not-supported/borgbackup.sh
  not-supported/daily-backup-wizard.sh
  not-supported/offshore-backup-wizard.sh
  not-supported/restore-backup.sh
  not-supported/rsyncbackup.sh
  not-supported/system-restore.sh
Labels: 3. to review

#1927 fix SC in master
  apps/bitwarden_registration.sh
Labels: 3. to review

#1922 reintroduce line breaks to specific command in activate-tls
  lets-encrypt/activate-tls.sh
Labels: 3. to review

#1932 fix APACHE_LOG_DIR
  apps/adminer.sh
  apps/bitwarden-rs.sh
  apps/collabora_docker.sh
  apps/onlyoffice_docker.sh
  apps/pico_cms.sh
  apps/talk.sh
  apps/tmbitwarden.sh
  lets-encrypt/activate-tls.sh
  nextcloud_install_production.sh
  not-supported/pi-hole.sh
Labels: 2. developing

#1934 add btrfs options to the not-supported folder
  not-supported/btrfs-format.sh
  not-supported/btrfs-mount.sh
  not-supported/not-supported_menu.sh
  not-supported/offshore-backup-wizard.sh
  not-supported/restore-backup.sh
  not-supported/rsyncbackup.sh
  not-supported/smbserver.sh
  not-supported/veracrypt-btrfs.sh
  not-supported/veracrypt-ntfs.sh
Labels: 3. to review

#1933 allow btrfs backup drives
  apps/clamav.sh
  not-supported/backup-viewer.sh
  not-supported/borgbackup.sh
  not-supported/daily-backup-wizard.sh
Labels: 3. to review
