Repository nextcloud/vm, pull requests merged in 2021-02, with the labels that each got.

#1793 system-restore - don't allow to restore on a different system
  not-supported/system-restore.sh
Labels: 3. to review

#1792 bitwarden_rs allow to reinstall also if files are present
  apps/bitwarden-rs.sh
Labels: 3. to review

#1789 update geoblock database files
  geoblockdat/2021-01-Maxmind-Country-IPv4.dat
  geoblockdat/2021-01-Maxmind-Country-IPv6.dat
Labels: 3. to review

#1796 ask to download the latest update script again
  menu/main_menu.sh
Labels: 3. to review

#1797 pihole - move update to its own script
  not-supported/pi-hole.sh
Labels: 3. to review

#1800 smbserver - get rid of members packet
  not-supported/smbserver.sh
Labels: 3. to review

#1805 ddclient - add no-ip
  network/ddclient-configuration.sh
Labels: 3. to review

#1804 Update geoblock database files
  geoblockdat/2021-02-Maxmind-Country-IPv4.dat
  geoblockdat/2021-02-Maxmind-Country-IPv6.dat
Labels: 3. to review

#1808 avoid double crontabs
  apps/clamav.sh
  lets-encrypt/test-new-config.sh
Labels: 3. to review

#1806 add a script to the not-supported folder
  not-supported/borgbackup.sh
  not-supported/remotedesktop.sh
  not-supported/restore-backup.sh
Labels: 3. to review

#1811 don't enable disabled apps after update
  nextcloud_update.sh
  old/recover_apps.py
Labels: 3. to review

#1812 fix a detail with the new app restore process
  nextcloud_update.sh
Labels: 3. to review

#1815 fix restore group settings for apps
  nextcloud_update.sh
Labels: 3. to review

#1816 geoblock - allow some scans
  network/geoblock.sh
Labels: 3. to review

#1821 fix watchtower updates
  lib.sh
  nextcloud_update.sh
Labels: 3. to review

#1822 geoblock - add lets encrypt advice
  network/geoblock.sh
Labels: 3. to review

#1823 fix upgrade.disable-web
  nextcloud_install_production.sh
Labels: 3. to review

#1827 don't break update when enabling app
  lib.sh
Labels: 3. to review

#1828 borg - fix pruning
  not-supported/borgbackup.sh
Labels: 3. to review

#1825 fix pecl php extensions
  addons/redis-server-ubuntu.sh
  nextcloud_install_production.sh
  nextcloud_update.sh
Labels: 3. to review

#1835 prevent apps from breaking the update due to incompatibility
  nextcloud_update.sh
Labels: 3. to review

#1817 Introduce notify_push in master
  apps/notify_push.sh
  lib.sh
  menu/additional_apps.sh
  not-supported/restore-backup.sh
Labels: 3. to review

#1843 enhance notify_push
  apps/notify_push.sh
Labels: 3. to review

#1845 add status flag for Notify Push
  menu/additional_apps.sh
Labels: 3. to review, Priority-1, bug

#1849 move extract to its own script
  apps/extract.sh
  menu/additional_apps.sh
  not-supported/restore-backup.sh
Labels: 2. developing

#1841 introduce whiteboard app in master
  apps/previewgenerator.sh
  apps/whiteboard.sh
  menu/additional_apps.sh
  not-supported/restore-backup.sh
Labels: 3. to review

#1848 move the incompatibility fix to a different place
  nextcloud_update.sh
Labels: 3. to review

#1850 make sure that all docker containers only listen on localhost
  apps/bitwarden-rs.sh
Labels: 3. to review

#1839 fix the --not-latest flag
  nextcloud-startup-script.sh
Labels: 3. to review

#1831 21.0.0
  CHANGELOG.md
Labels: 3. to review

#1852 clamav - give the daemon more time to start
  apps/clamav.sh
Labels: 3. to review

#1854 minor corrections
  apps/notify_push.sh
Labels: 3. to review

#1857 smbserver - completely rework how directories get mounted to Nextcloud
  not-supported/smbserver.sh
Labels: 3. to review

#1859 fix mc installation
  apps/midnight-commander.sh
Labels: 3. to review

#1861 smtp-mail - add providers
  addons/smtp-mail.sh
Labels: 3. to review

#1863 smbserver - add option to set user mail-address in Nextcloud
  not-supported/smbserver.sh
Labels: 3. to review

#1860 smtp-mail - make it possible to use the same settings in Nextcloud
  addons/smtp-mail.sh
Labels: 3. to review
