Repository nextcloud/vm, pull requests merged in 2022-01, with the labels that each got.

#2176 borgbackup - fix getting the snapshot usage
  not-supported/borgbackup.sh
Labels: bug, 3. to review

#2178 update geoblock database
  geoblockdat/2021-12-Maxmind-Country-IPv4.dat
  geoblockdat/2021-12-Maxmind-Country-IPv6.dat
Labels: enhancement, 3. to review

#2185 implement a notification for outdated Nextcloud versions
  nextcloud_update.sh
  static/updatenotification.sh
Labels: enhancement, 3. to review

#2193 plex - only mount dri device into the container if hardware transcodi…
  not-supported/plexmediaserver.sh
Labels: bug, 3. to review

#2200 fix adminer.sh #2195
  apps/adminer.sh
Labels: bug, 3. to review

#2206 add some docs how to increase the size of the root partition
  not-supported/daily-backup-wizard.sh
Labels: enhancement, 3. to review

#2199 fix zero byte files
  lets-encrypt/activate-tls.sh
  nextcloud_install_production.sh
Labels: enhancement, 2. developing

#2197 Replace elasticsearch in favor of opensearch as fts engine
  apps/fulltextsearch.sh
  apps/opensearch_certs.sh
  lib.sh
Labels: enhancement, 3. to review
