Repository nextcloud/vm, pull requests merged in 2022-02, with the labels that each got.

#2216 Add missing restart policy
  apps/fulltextsearch.sh
Labels: 3. to review

#2218 update janus repo url
  apps/talk.sh
Labels: 3. to review

#2222 smbserver - also delete empty folders when emptying the recycle bin
  not-supported/smbserver.sh
Labels: enhancement, 3. to review

#2225 improve error handling between different backup scripts
  nextcloud_update.sh
  not-supported/borgbackup.sh
  not-supported/pi-hole.sh
  not-supported/rsyncbackup.sh
Labels: enhancement, 3. to review

#2228 tmp2-unlock - make it work for all systems
  not-supported/tpm2-unlock.sh
Labels: bug, 3. to review

#2230 fix special characters
  not-supported/daily-backup-wizard.sh
  not-supported/veracrypt-btrfs.sh
  not-supported/veracrypt-ntfs.sh
Labels: bug, 3. to review

#2234 exporting a variable from a child process back to the parent process does not work
  addons/database_shrinking.sh
  nextcloud_update.sh
  not-supported/borgbackup.sh
  not-supported/pi-hole.sh
  not-supported/rsyncbackup.sh
  not-supported/system-restore.sh
Labels: bug, 3. to review
