Repository nextcloud/vm, pull requests merged in 2023-05, with the labels that each got.

#2486 update the geoblock database
  geoblockdat/2023-02-Maxmind-Country-IPv4.dat
  geoblockdat/2023-02-Maxmind-Country-IPv6.dat
Labels: 3. to review

#2487 Improve solvable_files.sh from Nextcloud GmbH
  addons/fix_invalid_modification_time.sh
  addons/solvable_files.sh
Labels: enhancement

#2496 fix onlyoffice setting jwt_secret
  apps/onlyoffice_docker.sh
Labels: bug, 3. to review

#2498 give plex user a fixed uid and gid
  not-supported/plexmediaserver.sh
Labels: bug, 3. to review

#2499 remotedesktop - remove gnome-shell-extensions which seem to be removed
  not-supported/remotedesktop.sh
Labels: bug, 3. to review

#2501 pi-hole - keep host headers
  not-supported/pi-hole.sh
Labels: bug, 3. to review
