Repository nextcloud/vm, pull requests merged in 2024-09, with the labels that each got.

#2661 update geoblock database - august 2024
  geoblockdat/2024-08-Maxmind-Country-IPv4.dat
  geoblockdat/2024-08-Maxmind-Country-IPv6.dat
Labels: dependencies

#2662 borg: install python3-pyfuse3
  not-supported/daily-backup-wizard.sh
  not-supported/restore-backup.sh
Labels: bug, 3. to review

#2683 Use IPInfo as secondary source
  lib.sh
  network/geoblock.sh
  nextcloud_update.sh
Labels: enhancement, 3. to review
